spring:
  application.name: capstone
  profiles:
    include: db, firebase

logging:
  level:
    org.hibernate.SQL: debug
    com.jbnu.capstone: debug

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
