spring:
  application.name: capstone
  profiles:
    include: db, firebase

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.hibernate.SQL: debug
    com.jbnu.capstone: debug
    com.zaxxer.hikari: debug

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
